fergana_name = ["фаргона", "фергана", "Farg'ona", "fargona"]
andijon_name = ["Andijon", "Anjan", "Андижон", "Андижан"]
tashkent_name = ["Tashkent", "Toshkent", "Tawkent", "Toshkend", "Tashkend", "Tashkendan", "Тошкент", "Ташкент",
                 "TOSHKENT", "TASHKENT", "ТАШКЕНТ", "ТОШКЕНТ"]
namangan_name = ["Namangan", "Наманган"]
sirdarya_name = ["Sirdaryo", "Сирдарйо", "Сардоба", "Сирдарё", "Сырдарья", "Guliston"]
jizzakh_name = ["Jizzax", "Jizzah", "Жиззах", "Джиззах", "Zomin"]
samarkand_name = ["Samarqand", "Samarqant", "Urgut", "Самарканд", "Самаркант"]
bukhara_name = ["Buxoro", "Бухоро", "Бухара"]
navoi_name = ["Navoi", "Navoiy", "Навои", "Наваи", "Навоий"]
kashkadarya_name = ["Qashqadaryo", "Qarshi", "Карши", "Кашкадарья"]
surkhandarya_name = ["Surxondaryo", "Termiz", "Сурхондарё", "Сурхандарья"]
xorezm_name = ["Xorazm", "Urganch", "Хорезм", "Урганч", "Хоразм"]
karakalpak_name = ["Qoraqalpoq", "Нукус", "Akcholak", "Каракалпак", "Nukus"]
