t_list = set()
f_list = set()
a_list = set()
n_list = set()
sirdarya_users = set()
jizzakh_users = set()
samarkand_users = set()
bukhara_users = set()
navoi_users = set()
kashkadarya_users = set()
surkhandarya_users = set()
xorezm_users = set()
karakalpak_users = set()

users_list = set()
