t_list = set()  # Toshkent
f_list = set()  # Farg'ona
a_list = set()  # Andijon
n_list = set()  # Namangan
sirdarya_users = set()
jizzakh_users = set()
samarkand_users = set()
bukhara_users = set()
navoi_users = set()
kashkadarya_users = set()
surkhandarya_users = set()
xorezm_users = set()
karakalpak_users = set()
kirgizistan_users = set()
tajikistan_users = set()
kazakstan_users = set()
rossia_users = set()
turkey_users = set()
china_users = set()
yevropa_users = set()
users_list = set()
